# Generated by Django 3.2.13 on 2022-07-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220720_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gamemode',
            field=models.CharField(default='none', max_length=15),
        ),
    ]
