# Generated by Django 3.2.13 on 2022-07-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_game_gamemode'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='legs',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
