# Generated by Django 3.2.13 on 2022-07-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_game_legs'),
    ]

    operations = [
        migrations.AddField(
            model_name='leg',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visit',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
