# Generated by Django 3.2.13 on 2022-07-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220723_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leg',
            name='winner',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
