# Generated by Django 3.2.13 on 2022-07-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220723_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='done',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='legs',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
